### ISSUE TITLE
Error in ./src/components/Join/Join.js

### ISSUE THREAD

**Issue by eriiksanjaya** [Rendydinar/quickchatting#3]
![Screenshot from 2020-05-18 10-48-21](https://user-images.githubusercontent.com/37096226/82172839-8ee4f300-98f5-11ea-8301-e532147525ec.png)
ini masalahnya di mana ya? saya awam di nodejs sama reactjs

**Comment by eriiksanjaya** [comment]
![Screenshot from 2020-05-18 10-55-34](https://user-images.githubusercontent.com/37096226/82173013-24808280-98f6-11ea-96df-e9aa858ffbd7.png)
sudah bisa, baris 42 saya naikin ke atas

**Comment by Rendydinar** [comment]
Itu karena variabel img salah penempatan pendefinisiannya. 

Baik Terima kasih untuk informasinya, saya sudah melakukan perbaikan.
